name: SonarQube Code Scan

on:
  push:
    branches:
      - main
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install SonarScanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=sonar-teams-alert \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://10.60.8.221:9000 \
            -Dsonar.token=$SONAR_TOKEN
